name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: backend
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Install just binary for running commands
        uses: taiki-e/install-action@just

      - uses: actions/checkout@v4

      - name: Set up Python using the python specified in pyproject.toml
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install front end dependencies from front end directory
        run: |
          cd theme/static_src
          npm i
          cd ../../

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.18"


      - name: Run tests
        run: |
          just test
        env:
          CI: true
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/backend"
